name: Resource pack release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set tag version
        id: app-version
        uses: paulhatch/semantic-version@v5.0.0-alpha2
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          change_path: "./"
      - run: gh release create $tag_name --title "Galaar resource pack"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.app-version.outputs.version_tag }}
